module.exports = {
    contentSecurityPolicy: {
        directives: {
            defaultSrc: ["'self'", 'data:', 'blob:', 'https:', 'ws:'],
            baseUri: ["'self'"],
            fontSrc: ["'self'", 'https:', 'data:'],
            scriptSrc: [
                "'self'",
                'https:',
                'http:',
                'blob:',
                'https://*.mapbox.com',
                'https://js.stripe.com',
                'https://m.stripe.network',
                'https://*.cloudflare.com',
            ],
            frameSrc: ["'self'", 'https://js.stripe.com'],
            objectSrc: ["'none'"],
            styleSrc: ["'self'", 'https:', "'unsafe-inline'"],
            workerSrc: [
                "'self'",
                'data:',
                'blob:',
                'https://*.tiles.mapbox.com',
                'https://api.mapbox.com',
                'https://events.mapbox.com',
                'https://m.stripe.network',
            ],
            childSrc: ["'self'", 'blob:'],
            imgSrc: ["'self'", 'data:', 'blob:'],
            formAction: ["'self'"],
            connectSrc: [
                "'self'",
                "'unsafe-inline'",
                'data:',
                'blob:',
                'https://*.stripe.com',
                'https://*.mapbox.com',
                'https://*.cloudflare.com/',
                'https://bundle.js:*',
                'ws://127.0.0.1:*/',
            ],
            upgradeInsecureRequests: [],
        },
    },
};
